### ISSUE TITLE
Length cannot be less than zero.

### ISSUE THREAD

**Issue by JerAleman** [timtester123/M3U_to_STRM#1]
Failed to parse line: https://dumxxxxxxx.com/movie/xxxxxxxxx/xxxxxxxx/xxxxxxx
Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at M3U_to_STRM.Module1.Main()
mscorlib

**Comment by ianc1989** [comment]
i have this same issue. how do we solve this??
