### ISSUE TITLE
tvg-name ending with a dot causes crash

### ISSUE THREAD

**Issue by trix7777** [timtester123/M3U_to_STRM#1]
Cool project! Found a bug:

Sample code from my m3u8:
#EXTINF:-1 tvg-id="" tvg-name="Avengers: Infinity War  [2018] ." tvg-logo="http://ip.nl:1234/images/movies//img.jpg" group-title="VOD: Avengers",Avengers: Infinity War  [2018] .
http://ip.tv:1234/movie/ABCD/EFGH/40729.mkv

CMD output:
Fehler: Could not find a part of the path 'C:\tmp\test\Filme\Avengers Infinity War  [2018] \Avengers Infinity War  [2018] ..strm'.
Fehler:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at Microsoft.VisualBasic.FileIO.FileSystem.WriteAllText(String file, String text, Boolean append, Encoding encoding)
   at Microsoft.VisualBasic.MyServices.FileSystemProxy.WriteAllText(String file, String text, Boolean append)
   at M3U_to_STRM.Module1.Main()

**Comment by timtester123** [comment]
Hi, thanks for reporting.
Fixed it in v.1.2.0.0

**Comment by trix7777** [comment]
Cool! Thanks for fixing that =)
Do you mind if I fork your project and modify it for another provider?

**Comment by timtester123** [comment]
Feel free to fork and modify this project, but it should work with other providers without modification.

**Comment by trix7777** [comment]
Thanks! Yeah, it's maybe more of a customization, like removing everything that has to do with TV and only keep VOD and Series, for instance:
If (line1.ToLower.StartsWith("#extinf:") AndAlso
line1.ToLower.Contains("series: english [multi-sub]") Or
line1.ToLower.Contains("series: nordic") Or
(line1.ToLower.Contains("vod:") AndAlso
Not line1.ToLower.Contains("vod: albania") And
Not line1.ToLower.Contains("vod: arabic") And
etc...

Alternatively, later, add unwanted groups into external file.
Also other stuff I do not want to bother you with; like for instance atm you replace ":" with nothing, which makes titles like "Alien 5:Prometheus [2012]" to become "Alien 5Prometheus [2012]". I know, the provider should have made a space after ":" but I think some chars better be exchanged for others, like in this case, it's imo better solved by replacing ":" with "-".

Thanks again!

**Comment by timtester123** [comment]
Okay, do what you want and have fun.
